###
GET  https://localhost:8443/

###
POST  https://localhost:8443/api/user/signup
Content-Type: application/json

{
  "DisplayName" : "Demo Man",
	"UserName"    : "demo",
	"Email"       : "demo@localhost",
	"Password"    : "123456"
}

###
POST  https://localhost:8443/api/user/signin
Content-Type: application/json

{
	"Email"       : "demo@localhost",
	"Password"    : "123456"
}

###
GET  https://localhost:8443/api/user/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3NDI3MjAsIlRva2VuTGV2ZWwiOiIwIiwiSW5mbyI6eyJFbWFpbCI6ImRlbW9AbG9jYWxob3N0IiwiS2luZCI6Imh1bWFuIn19.igBu4c0bflLTASMIwrhoKyDyvLLqvUvFuO1VelbcQO4

###
GET  https://localhost:8443/api/user/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3NDI3MjAsIlRva2VuTGV2ZWwiOiIwIiwiSW5mbyI6eyJFbWFpbCI6ImRlbW9AbG9jYWxob3N0IiwiS2luZCI6Imh1bWFuIn19.igBu4c0bflLTASMIwrhoKyDyvLLqvUvFuO1VelbcQO4

###
GET  https://localhost:8443/api/image/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3NzUwMzQsIlRva2VuTGV2ZWwiOiIwIiwiSW5mbyI6eyJFbWFpbCI6ImRlbW9AbG9jYWxob3N0IiwiS2luZCI6Imh1bWFuIn19.sZ1ucrwjFJ65b-aSSrp7KKzTcenjz4iAGQXTVJiGTCI



###
POST  https://localhost:8443/api/image/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3NjgxMTUsIlRva2VuTGV2ZWwiOiIwIiwiSW5mbyI6eyJFbWFpbCI6ImRlbW9AbG9jYWxob3N0IiwiS2luZCI6Imh1bWFuIn19.UYLbG3XDNGvBrWwTi0dUfZjHTxD9OQNk9-uSAmnNT5s

{
	"test" : "dummy"
}