###
GET  https://localhost:8443/

###
POST  https://localhost:8443/api/user/signup
Content-Type: application/json

{
  "DisplayName" : "Demo Man",
	"UserName"    : "demo",
	"Email"       : "demo@localhost",
	"Password"    : "123456"
}

###
POST  https://localhost:8443/api/user/signin
Content-Type: application/json

{
	"Email"       : "demo@localhost",
	"Password"    : "123456"
}